name: Build and Publish

on: 
 workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        go-version: [1.20]

        os: [linux]

        arch: [386, amd64, arm64, ppc64le, mips, mipsle]

    steps:

    - name: Checkout

      uses: actions/checkout@v3

    - name: Setup Go

      uses: actions/setup-go@v3

      with:

        go-version: ${{ matrix.go-version }}

    - name: Build Binary

      env:

        GOOS: ${{ matrix.os }}

        GOARCH: ${{ matrix.arch }}

      run: |

        go build -o "bin/{{.OS}}/{{.Arch}}/{{.Name}}" -ldflags "-w -s" .

    - name: Compress Binary

      env:

        OS: ${{ matrix.os }}

        ARCH: ${{ matrix.arch }}

        BIN_NAME: ${{ env.GITHUB_REPOSITORY}}

        DIR_NAME: ${{ env.GITHUB_REPOSITORY}}-latest

        COMPRESSED_FILE_EXT: ""

      run: |

        if [ $OS == "windows" ]; then

          COMPRESSED_FILE_EXT="zip"

        else

          COMPRESSED_FILE_EXT="tar.gz"

        fi

        FILE_NAME="${BIN_NAME}_${OS}_${ARCH}.${COMPRESSED_FILE_EXT}"

        [ -d $DIR_NAME/$OS ] || mkdir -p $DIR_NAME/$OS

        [ -f $DIR_NAME/$OS/$FILE_NAME ] && rm $DIR_NAME/$OS/$FILE_NAME

        if [ $OS == "windows-latest" ]; then

          zip $DIR_NAME/$OS/$FILE_NAME -r bin/$OS/$ARCH/

        else

          tar -czf $DIR_NAME/$OS/$FILE_NAME -C bin/$OS/$ARCH/ .

        fi

    - name: Publish Binary

      uses: actions/upload-artifact@v2.2.4

      with:

        name: ${{ env.GITHUB_REPOSITORY}}_${{ matrix.os }}_${{ matrix.arch }}

        path: ${{ env.GITHUB_REPOSITORY}}-latest/${{ matrix.os }}/
